### ISSUE TITLE
All memo randum

### ISSUE THREAD

**Issue by shinichi-takayanagi** [shinichi-takayanagi/oregpt#6]
## todos
- [x] UI change
- [x] Ctrl+C etc (try catch)
- [x] add pre-commit
- [x] Refactor commands (command class?)
- [x] `load` command
- [x] Add more test
- [x] Documentation
- [x] Introduce Click lib
- [x] Change the behavior of Ctrl+C and Shift+Command
- [x] System bot setting
- [ ] copy the github actions https://github.com/horoiwa/ProjectBoilerPlate
- [ ] github actions release https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml
- [ ] Refactor backend (name convention ai, assistant, chatbot, langchain or google's one)
- [ ] Add more backends(Claude, Palm etc)
- [ ] update commaneds (beautify `/history` , typo suggestion)
## Unsolved
- How to ignore `tests` directory based on `pyproject.toml` mypy + pre-commit
    - https://github.com/pre-commit/mirrors-mypy/issues/1
## useful links
- https://python-prompt-toolkit.readthedocs.io/en/master/index.html

**Comment by shinichi-takayanagi** [comment]
useful links
- https://python-prompt-toolkit.readthedocs.io/en/master/index.html

**Comment by fstorino** [comment]
Hi there! Thank you for this tool! I'm new to github so I don't know the proper way to report this, but there are two misspellings of "history" ("hisotry") in the `command.py` file that appear in the `/help` command (it shows in the animated gif in `README.md` as well).

**Comment by shinichi-takayanagi** [comment]
@fstorino 
Thank you for reporting!
I will fix that quickly with other functional extensions!
